apiVersion: v1
kind: Secret
metadata:
  name: products-microservice-secret
  namespace: cloud
type: Opaque
stringData:
  host: cloud-db-service
  username: products_manager
  password: products_password